services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: performance-demo-symfony7-php
    working_dir: /app
    volumes:
      - .:/app
      - ../../:/bundles
      - composer-cache:/root/.composer/cache
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DATABASE_URL=mysql://${MYSQL_USER:-demo_user}:${MYSQL_PASSWORD:-password}@mysql:3306/${MYSQL_DATABASE:-performance_demo}?serverVersion=8.0&charset=utf8mb4
      - APP_ENV=dev
    command: ["php-fpm", "-F"]
    networks:
      - performance-demo-network

  nginx:
    image: nginx:alpine
    container_name: performance-demo-symfony7-nginx
    volumes:
      - .:/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - performance-demo-network

  mysql:
    image: mysql:8.0.36
    container_name: performance-demo-symfony7-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-performance_demo}
      MYSQL_USER: ${MYSQL_USER:-demo_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - performance-demo-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 5s
      timeout: 3s
      retries: 10

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  composer-cache:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
    driver: local

networks:
  performance-demo-network:
    driver: bridge
